@part1 = [
	"Wir", 
	"Sie", 
	"Die Vorstandsmitglieder", 
	"Die Mitarbeiter aus dem Business Development", 
	"Die Roadwarrior", 
	"Die Sales-Guys",
	"Die Mitglieder der Arbeitsgruppe",
	"Die Hands-On-People",
	"Die Player",
	"Die neuen Doppelspitzen",
	"Die neuen Allies",
	"Unsere Partner",
	"Die High-Potentials",
	"Die Rank&File-Troops",
	"Die Kollegen aus dem Marketing",
	"Die Leute von R&D",
	"Die Project-Members",
	"Die Projektpartner",
	"Die Leute in unserem Core-Team",
	"Die Project-Leads",
	"Die Scrum-Master",
	"Wir alle",
	"Die Global Player",
	"Die Stakeholder",
	"Die Leute von der Cyber-Security",
	"Die Mitglieder des Cyber Security Operation Center"
]

@part2 = [
	"müssen", 
	"sollten", 
	"wollen", 
	"werden", 
	"dürfen", 
	"können",
	"möchten",
	"mögen doch bitte"
]

@part3 = [
	"heute", 
	"morgen", 
	"schnellstmöglich", 
	"bald", 
	"immer wieder", 
	"demnächst", 
	"am Ende des Tages", 
	"ein Stück weit", 
	"proaktiv", 
	"mit Prio", 
	"absolut", 
	"mit Bordmitteln", 
	"beim Business-Lunch",
	"anyway",
	"maximal",
	"definitiv",
	"auf der Tonspur",
	"in der Porzellanabteilung",
	"perfomance-driven",
	"bei einem Bierchen",
	"im Workshop",
	"safe",
	"FYI",
	"für das Board",
	"asap",
	"auf dem Schirm",
	"zeitnah",
	"ergebnisoffen",
	"mit Luft nach oben",
	"mit tougher Deadline",
	"zielgerichtet",
	"zielgruppengerecht",
	"ressourcenschonend",
	"bis EOM",
	"mit dem richtigen Commitment",
	"fokussiert",
	"mit Blick auf das Target",
	"vom Doing her",
	"ohne überflüssige Research",
	"rudderless",
	"disruptive",
	"perfectly aligned",
	"sweet",
	"maintainable",
	"strategic",
	"etwas haptischer",
	"bis EOB",
	"vor next BD",
	"auf der aktuellen Direction",
	"world-class",
	"on-premise",
	"mit minimaler Abhängigkeit",
	"final",
	"best practice",
	"best-of-breed",
	"best-in-class",
	"wertschöpfend",
	"kundenorientiert",
	"ergebnisorientiert",
	"at the end of the day",
	"dynamic",
	"reaktiv",
	"competitive",
	"off the shelf",
	"service oriented",
	"asapst",
	"im wahrsten Sinne des Wortes",
	"buchstäblich",
	"wie gesagt",
	"direkt nach einem ersten Durchstich"
]

@part4 = [
	"die neuen Kollegen", 
	"den CTO aus Bonn", 
	"Heinrich", 
	"das neue Projekt", 
	"den Business Case", 
	"den Fünfjahresplan", 
	"das Vertriebsteam", 
	"die Auszubildende", 
	"den Auszubildenden", 
	"die nächsten Schritte", 
	"die Bullet-Points", 
	"die Short-List", 
	"den Flow", 
	"einen Slot", 
	"die To-Dos", 
	"den Abstimmungsprozess", 
	"unsere Line-Extension",
	"den Change-Request", 
	"den Benchmark",
	"die Deadline",
	"unsere Credibility",
	"die Connectivity",
	"die Must-Haves",
	"die Insights",
	"die Visibilität",
	"den neuen Prozess",
	"die Leadership-Aufgaben",
	"die Pace",
	"eine Recommendation aus der Audience",
	"den Workshop",
	"das Briefing",
	"ein Get-Together",
	"unsere Exit-Strategie", 
	"die Keynote",
	"ein Update",
	"ein absolutes No-Go",
	"die next Steps",
	"den hidden Champion",
	"mehr Airtime",
	"den early Bird",
	"das All-Time-High",
	"den Overhead",
	"den inner Circle",
	"den No-Brainer",
	"ein Bio-Break",
	"mehr Wiggle-Room",
	"höhere Performance",
	"das Wording",
	"die Skills",
	"den High-Potential",
	"die Location",
	"neue Action-Items",
	"die Synergie-Effekte",
	"unsere Kernkompetenzen",
	"die Pipeline",
	"die Zielgruppe",
	"die Stati",
	"die Szenarios",
	"die Opportunity",
	"das Target",
	"das operative Doing",
	"das tighte Project",
	"die Slides",
	"die Responsibilities",
	"den Footprint",
	"die neue Structure",
	"den broad Consensus",
	"den Low-Level-Stuff",
	"die Kapazitäten",
	"mehr Kapa",
	"die To-Market-Strategy",
	"diesen Approach",
	"das Outcome",
	"den neuen Onboarding-Flow",
	"den aktuellen Invoice",
	"die Maintenance",
	"die Measures",
	"mehr Repeat-Visits",
	"die Long-Term-Strategy",
	"den Polish",
	"die neuen Funktionalitäten",
	"die Figures",
	"den Forecast",
	"das Sign-off-Meeting",
	"ne saubere 80/20-Decision",
	"den fixen Approach",
	"ein Skip-Level-Meeting",
	"die unfiltered Impressions",
	"das Regional-HQ",
	"die High-Priority-Actionables",
	"neue Ventures",
	"die loose Ends",
	"das Topic",
	"eine Greenfield-Solution",
	"das Big Picture",
	"eine Turnkey-Solution",
	"das conceptual Lift-off",
	"die mission-critical Response",
	"die digitale Transformation",
	"das revisionssichere Audit-Log",
	"die On-Premise-Deployments",
	"die stabile Multi-Cloud",
	"den Elevator-Pitch",
	"die SEO-Optimierung",
	"den neuen Gold-Standard",
	"das Regel-Meeting",
	"den Schwarzen Peter",
	"das Outplacement",
	"den Value",
	"eine Win-Win Situation",
	"den Support",
	"das Issue",
	"die Visionen",
	"die Brainstorming-Methoden",
	"die Destination",
	"die Problematik",
	"eine Risikoanalyse",
	"einen Audit",
	"den Milestone",
	"die Differentiation",
	"das E-Commerce Outsourcing",
	"die Policies",
	"das Team-Building",
	"das B2B",
	"das Customer Facing",
	"den Growth",
	"die Communication",
	"das A-B-Testing",
	"die Perspective",
	"die Target-Audience",
	"die Front-Lines",
	"die Profitability",
	"das Engagement",
	"unsere Legacy-Anwendungen",
	"den Cyber",
	"die Cyber-Weapons",
	"mehr Cyber-Security",
	"die Disruption"
]

@part5 = [
	"auf", 
	"ein", 
	"zu", 
	"um", 
	"zer", 
	"ver", 
	"be", 
	"aus", 
	"ent", 
	"er", 
	"durch", 
	"nach",
	"voran",
	"rück",
	"raus",
	"triple",
	"right",
	"über",
	"hoch",
	"over",
	"under",
	"out",
	"in",
	"quer",
	"multi",
	"cyber"
]

@part6 = [
	"schlauen", 
	"phasen", 
	"gleisen", 
	"grooven", 
	"peilen", 
	"lasten", 
	"steuern", 
	"callen", 
	"spaßen", 
	"gehen", 
	"booten", 
	"planen", 
	"rechten", 
	"stärken",
	"treiben",
	"koppeln",
	"galoppieren",
	"holen",
	"adressieren",
	"reporten",
	"beefen",
	"benchmarken",
	"händeln",
	"setzen",
	"rollen",
	"kippen",
	"dichten",
	"evaluieren",
	"adaptieren",
	"bringen",
	"briefen",
	"testen",
	"hübschen",
	"halten",
	"canceln",
	"laden",
	"lesen",
	"schauen",
	"stielen",
	"führen",
	"handlen",
	"vollziehen",
	"pampern",
	"platzieren",
	"schedulen",
	"fokussieren",
	"runnen",
	"checken",
	"sweaten",
	"joinen",
	"languagen",
	"leaden",
	"disrupten",
	"liften",
	"speichern",
	"priorisieren",
	"loopen",
	"boxen",
	"targeten",
	"pricen",
	"requesten",
	"investen",
	"takten",
	"monitoren",
	"forcen",
	"finden",
	"stressen",
	"branden",
	"kommunizieren",
	"scoren",
	"aggregieren",
	"usen",
	"pfeifen",
	"proben",
	"cybern",
	"schärfen",
	"stechen"
]

@part7 = [
	".", 
	"!", 
	", ja.",
	", das wäre ja gelacht.",
	", da mache ich mir keinen Kummer."
]
